---
- hosts: 'all'
  vars:
    bin: '{{ ansible_env.PWD }}/bin'
    install: '{{ ansible_env.PWD }}/install'
    cellar: '/home/linuxbrew/.linuxbrew/Cellar'
  tasks:
  - name: 'apt: update'
    apt:
      update_cache: true
    become: true

  - name: 'apt: install'
    apt:
      name:
      - 'ssh-askpass'
      state: 'latest'
    become: true

  - name: 'brew: install'
    homebrew:
      name:
      - 'jq'
      - 'ansible'
      - 'neovim'
      - 'shellcheck'
      - 'tmux'
      - 'ripgrep'
      - 'go'
      state: 'latest'

  - name: '1password-cli'
    shell: '{{ install }}/1password-cli.bash'
    register: 'op_shell'
    changed_when: '"already installed" not in op_shell.stdout'

  - name: 'golangci-lint'
    shell: '{{ install }}/golangci-lint.bash'
    register: 'golangci_lint_shell'
    changed_when: '"already installed" not in golangci_lint_shell.stdout'

  - name: 'env: bash'
    lineinfile:
      path: '~/.bashrc'
      line: '{{ item }}'
    with_items:
    - 'export PATH="{{ bin }}:${PATH}"'
    - 'export PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"'
    - 'export EDITOR="nvim"'
    - 'export GOROOT="{{ cellar }}/go/$( go version | rg -o "1\.\d+(\.\d+)?" )/libexec"'
    - 'export GOPATH="${HOME}/go"'
    - 'export PATH="${GOPATH}/bin:${PATH}"'
    
